DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS balance;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE balance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  amount INTEGER DEFAULT 0
);